try:
    int("ala")
except Exception as e:
    print(e)

